namespace AillieoUtils.EasyBehaviorTree.Creator
{
    public static class CodeTemplate
    {

        public static readonly string head =
            @"// This script is generated by *NodeParamGenerator*
// Any modifications in this script will be lost after regeneration.
";

        public static readonly string filename = @"{0}ParamSet.cs";

        public static readonly string nodeParamTempate =
            @"namespace AillieoUtils.EasyBehaviorTree.Creator
{{

    [System.Serializable]
    public class {1}Param : NodeParam<{0}>
    {{
    }}

    [System.Serializable]
    public class {1}ParamSet : NodeParamSet<{1}Param, {0}>
    {{
    }}
}}
";


        public static readonly string nodeDefineTemplate0 =
            @"using System.Collections.Generic;
using UnityEngine;
using UnityEditor;
using System;
using System.Reflection;

namespace AillieoUtils.EasyBehaviorTree.Creator
{{
    public partial class NodeDefine : MonoBehaviour
    {{

#if UNITY_EDITOR

        // =============================================================================================================================

        [HideInInspector][SerializeField]
        public EnumParamSet mEnumParamSet = new EnumParamSet();
{0}
        // =============================================================================================================================

        private NodeDefine()
        {{
            cachedMappings = new Dictionary<Type, NodeParamSetAndName>()
            {{
                // =============================================================================================================================

                {{typeof(Enum),new NodeParamSetAndName() {{ set = mEnumParamSet,name = ""mEnumParamSet"" }} }},
{1}
                // =============================================================================================================================
            }};
        }}
#endif

    }}
}}
";


        public static readonly string nodeDefineTemplate1 =
            @"        [HideInInspector][SerializeField]
        public {0}ParamSet {1}ParamSet = new {0}ParamSet();
";


        public static readonly string nodeDefineTemplate2 =
            @"                {{typeof({2}),new NodeParamSetAndName(){{set={1}ParamSet,name = ""{1}ParamSet"" }} }},
";

    }
}
