// This script is generated by *NodeParamGenerator*
// Any modifications in this script will be lost after regeneration.
namespace EasyBehaviorTree.Creator
{

    [System.Serializable]
    public class BoolArrayParam : NodeParam<bool[]>
    {
    }

    [System.Serializable]
    public class BoolArrayParamSet : NodeParamSet<BoolArrayParam, bool[]>
    {
    }
}
