// This script is generated by *NodeParamGenerator*
// Any modifications in this script will be lost after regeneration.
namespace AillieoUtils.EasyBehaviorTree.Creator
{

    [System.Serializable]
    public class BoolParam : NodeParam<bool>
    {
    }

    [System.Serializable]
    public class BoolParamSet : NodeParamSet<BoolParam, bool>
    {
    }
}
