// This script is generated by *NodeParamGenerator*
// Any modifications in this script will be lost after regeneration.
namespace AillieoUtils.EasyBehaviorTree.Creator
{

    [System.Serializable]
    public class FloatParam : NodeParam<float>
    {
    }

    [System.Serializable]
    public class FloatParamSet : NodeParamSet<FloatParam, float>
    {
    }
}
