// This script is generated by *NodeParamGenerator*
// Any modifications in this script will be lost after regeneration.
namespace EasyBehaviorTree.Creator
{

    [System.Serializable]
    public class IntArrayParam : NodeParam<int[]>
    {
    }

    [System.Serializable]
    public class IntArrayParamSet : NodeParamSet<IntArrayParam, int[]>
    {
    }
}
