// This script is generated by *NodeParamGenerator*
// Any modifications in this script will be lost after regeneration.
namespace AillieoUtils.EasyBehaviorTree.Creator
{

    [System.Serializable]
    public class IntParam : NodeParam<int>
    {
    }

    [System.Serializable]
    public class IntParamSet : NodeParamSet<IntParam, int>
    {
    }
}
