// This script is generated by *NodeParamGenerator*
// Any modifications in this script will be lost after regeneration.
namespace AillieoUtils.EasyBehaviorTree.Creator
{

    [System.Serializable]
    public class LongArrayParam : NodeParam<long[]>
    {
    }

    [System.Serializable]
    public class LongArrayParamSet : NodeParamSet<LongArrayParam, long[]>
    {
    }
}
