// This script is generated by *NodeParamGenerator*
// Any modifications in this script will be lost after regeneration.
namespace EasyBehaviorTree.Creator
{

    [System.Serializable]
    public class StringArrayParam : NodeParam<string[]>
    {
    }

    [System.Serializable]
    public class StringArrayParamSet : NodeParamSet<StringArrayParam, string[]>
    {
    }
}
