// This script is generated by *NodeParamGenerator*
// Any modifications in this script will be lost after regeneration.
namespace AillieoUtils.EasyBehaviorTree.Creator
{

    [System.Serializable]
    public class StringParam : NodeParam<string>
    {
    }

    [System.Serializable]
    public class StringParamSet : NodeParamSet<StringParam, string>
    {
    }
}
