// This script is generated by *NodeParamGenerator*
// Any modifications in this script will be lost after regeneration.
namespace AillieoUtils.EasyBehaviorTree.Creator
{

    [System.Serializable]
    public class UnityEngine_Vector2ArrayParam : NodeParam<UnityEngine.Vector2[]>
    {
    }

    [System.Serializable]
    public class UnityEngine_Vector2ArrayParamSet : NodeParamSet<UnityEngine_Vector2ArrayParam, UnityEngine.Vector2[]>
    {
    }
}
