// This script is generated by *NodeParamGenerator*
// Any modifications in this script will be lost after regeneration.
namespace AillieoUtils.EasyBehaviorTree.Creator
{

    [System.Serializable]
    public class UnityEngine_Vector3Param : NodeParam<UnityEngine.Vector3>
    {
    }

    [System.Serializable]
    public class UnityEngine_Vector3ParamSet : NodeParamSet<UnityEngine_Vector3Param, UnityEngine.Vector3>
    {
    }
}
