// This script is generated by *NodeParamGenerator*
// Any modifications in this script will be lost after regeneration.
namespace AillieoUtils.EasyBehaviorTree.Creator
{

    [System.Serializable]
    public class UnityEngine_Vector2Param : NodeParam<UnityEngine.Vector2>
    {
    }

    [System.Serializable]
    public class UnityEngine_Vector2ParamSet : NodeParamSet<UnityEngine_Vector2Param, UnityEngine.Vector2>
    {
    }
}
